<a href="https://colab.research.google.com/github/LxYuan0420/nlp/blob/main/notebooks/flair/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install flair

##### Tutorial 4: List of All Word Embeddings

This is not so much a tutorial, but rather a list of all embeddings that we currently support in Flair. Click on each embedding in the table below to get usage instructions. We assume that you're familiar with the base types of this library as well as standard word embeddings, in particular the StackedEmbeddings class.

###### Overview

All word embedding classes inherit from the TokenEmbeddings class and implement the embed() method which you need to call to embed your text. This means that for most users of Flair, the complexity of different embeddings remains hidden behind this interface. Simply instantiate the embedding class you require and call embed() to embed your text.

The following word embeddings are currently supported:

https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md

###### Combining BERT and Flair
You can very easily mix and match Flair, ELMo, BERT and classic word embeddings. All you need to do is instantiate each embedding you wish to combine and use them in a StackedEmbedding.

For instance, let's say we want to combine the multilingual Flair and BERT embeddings to train a hyper-powerful multilingual downstream task model. First, instantiate the embeddings you wish to combine:

In [4]:
from flair.embeddings import FlairEmbeddings, TransformerWordEmbeddings

# init Flair embeddings
flair_forward_embedding = FlairEmbeddings('multi-forward')
flair_backward_embedding = FlairEmbeddings('multi-backward')

# init multilingual BERT
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/714M [00:00<?, ?B/s]

Now instantiate the StackedEmbeddings class and pass it a list containing these three embeddings.

In [6]:
from flair.embeddings import StackedEmbeddings

# now create the StackedEmbedding object that combines all embeddings
stacked_embeddings = StackedEmbeddings(
    embeddings=[flair_forward_embedding, flair_backward_embedding, bert_embedding])

That's it! Now just use this embedding like all the other embeddings, i.e. call the embed() method over your sentences.

In [8]:
from flair.data import Sentence

sentence = Sentence("The grass is green.")

stacked_embeddings.embed(sentence)

for token in sentence:
    print(token)
    print(token.embedding)

Token[0]: "The"
tensor([ 0.6800,  0.2429,  0.0012,  ...,  0.5011, -0.1725,  0.1523])
Token[1]: "grass"
tensor([ 2.9200e-01,  2.2066e-02,  4.5290e-05,  ...,  7.1819e-01,
        -4.6009e-01,  5.7471e-01])
Token[2]: "is"
tensor([-0.5447,  0.0229,  0.0078,  ...,  0.7923, -0.1586,  0.6492])
Token[3]: "green"
tensor([0.1477, 0.1097, 0.0009,  ..., 0.6716, 0.0342, 0.1898])
Token[4]: "."
tensor([-1.5555e-01,  6.7598e-03,  5.3829e-06,  ...,  3.1035e-01,
         2.0151e-01,  2.2258e-01])


In [11]:
type(sentence[0].embedding)

torch.Tensor

In [12]:
sentence[0].embedding.shape

torch.Size([4864])

##### Trying out Flair multi-forward embedding

In [17]:
sample = Sentence("The grass is black.")

flair_forward_embedding.embed(sample)

[Sentence: "The grass is black ."]

In [18]:
for token in sample:
    print(token)
    print(token.embedding)
    print(token.embedding.shape)

Token[0]: "The"
tensor([ 0.6800,  0.2429,  0.0012,  ...,  0.0013, -0.0017,  0.0170])
torch.Size([2048])
Token[1]: "grass"
tensor([ 2.9200e-01,  2.2066e-02,  4.5290e-05,  ...,  7.5839e-05,
        -4.8159e-03,  5.5644e-02])
torch.Size([2048])
Token[2]: "is"
tensor([-5.4467e-01,  2.2940e-02,  7.7620e-03,  ...,  3.9666e-04,
        -1.7789e-03,  4.2921e-03])
torch.Size([2048])
Token[3]: "black"
tensor([ 0.7233,  0.1093,  0.0052,  ...,  0.0008, -0.0042,  0.0259])
torch.Size([2048])
Token[4]: "."
tensor([ 9.6559e-02, -1.5475e-02,  6.8737e-06,  ..., -2.2093e-02,
         4.7708e-02, -5.6382e-04])
torch.Size([2048])


Words are now embedded using a concatenation of three different embeddings. This means that the resulting embedding vector is still a single PyTorch vector.

Next
You can now either look into document embeddings to embed entire text passages with one vector for tasks such as text classification, or go directly to the tutorial about loading your corpus, which is a pre-requirement for training your own models.